name: Deploy Hugo Site to Cloudflare Pages

on:
  push:
    branches:
      - main  # 监听 main 分支的 push 事件
  workflow_dispatch:  # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Hugo
        run: |
          HUGO_VERSION=0.125.7
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
          tar -xvf hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
          chmod +x hugo
          mv hugo /usr/local/bin/hugo

      - name: Build Hugo site
        run: |
          for i in {1..3}; do
            hugo --gc --minify && break || sleep 10
          done

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          projectName: baoliba-in
          directory: public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          environment: production
